# escape=`

FROM mcr.microsoft.com/windows/nanoserver:10.0.14393.2007

SHELL ["powershell", "-Command"]

COPY vcruntime140.dll C:/Windows/System32/

COPY setup-nodejs.ps1 C:/
RUN C:\setup-nodejs.ps1

COPY setup.ps1 C:/
RUN C:\setup.ps1
