# escape=`

FROM mcr.microsoft.com/windows/servercore:10.0.14393.3866

SHELL ["powershell", "-Command"]

COPY *.dll C:/Windows/System32/

COPY setup-nodejs.ps1 C:/
RUN C:\setup-nodejs.ps1

COPY setup.ps1 C:/
RUN C:\setup.ps1
