#!/bin/sh

set -o errexit

docker --version || (
    echo Please install Docker. >&2
    exit 1
)

docker run --rm --volume "$(CDPATH= cd -- "$(dirname -- "$0")" && cd .. && pwd)":/app --workdir /app/src mlocati/powershell-phpmanager-src:latest make
