name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  powershell:
    name: PowerShell
    runs-on: windows-latest
    steps:
      - name: Initialize
        shell: powershell
        run: |
          $ErrorActionPreference = 'stop'
          if (Test-Path -PathType Container -LiteralPath C:\tools\php) {
            Remove-Item -Force -Recurse -LiteralPath C:\tools\php
          }
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup
        shell: powershell
        run: .\test\setup.ps1
      - name: Test
        shell: powershell
        run: |
          $pesterResult = .\test\pester.ps1
          if ($pesterResult.FailedCount -ne 0) {
            throw "$($pesterResult.FailedCount) tests failed!"
          }
  powershellcore:
    name: PowerShell Core
    runs-on: windows-latest
    steps:
      - name: Initialize
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          if (Test-Path -PathType Container -LiteralPath C:\tools\php) {
            Remove-Item -Force -Recurse -LiteralPath C:\tools\php
          }
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup
        shell: pwsh
        run: .\test\setup.ps1
      - name: Test
        shell: pwsh
        run: |
          $pesterResult = .\test\pester.ps1
          if ($pesterResult.FailedCount -ne 0) {
            throw "$($pesterResult.FailedCount) tests failed!"
          }
  docker:
    strategy:
      matrix:
        DOCKER_IMAGE:
        - nanoserver
        - windowsservercore
    name: Docker - ${{ matrix.DOCKER_IMAGE }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup
        env:
          DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        shell: powershell
        run: '& ".\test\Dockerfile.$Env:DOCKER_IMAGE.ps1"'
      - name: Test
        env:
          DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        shell: powershell
        run: |
          $volume="$($Env:GITHUB_WORKSPACE):C:\App"
          docker run --rm --volume $volume --workdir C:\App --env "PM_TEST_DOCKER=1" phpmanager/test powershell.exe 'Set-Location -LiteralPath C:\App; $pesterResult=.\test\pester.ps1; exit $pesterResult.FailedCount'
          $failCount = $LASTEXITCODE
          if ($failCount -ne 0) {
            throw "$failCount tests failed!"
          }
